"use client"
import './globals.css'
import { Inter , Roboto ,Varela_Round, Merriweather} from 'next/font/google'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { useState } from 'react'
const inter = Inter({ subsets: ['latin'] })

const roboto = Roboto( {subsets: ['latin'] ,
weight: '400',
});



const varel = Varela_Round({subsets:['latin'],
  weight: '400'
});

  const merri = Merriweather({subsets:['latin'],
  weight :'400'
});



// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {

  const [myfont,setMyFont] = useState('merri');
  const handleFont = (value)=>{
    setMyFont(value);
    
  }
  return (
    <html lang="en">
      <body className={myfont.className}>
        {/* <div className='w-full'> */}
          <Navbar handleFont={handleFont}></Navbar>
        {children}
        <Footer></Footer>
        {/* </div> */}
        </body>
    </html>
  )
}
